<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <RootNamespace>QuantumNetLib</RootNamespace>
    <AssemblyName>QuantumNetLib</AssemblyName>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
    <Nullable>disable</Nullable>
  </PropertyGroup>
</Project>
